name: Security & Dependency Checks

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]
    schedule:
        # Run security checks daily at 2 AM UTC
        - cron: "0 2 * * *"

jobs:
    security-audit:
        name: Security Audit
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"
 
            - name: Install dependencies
              run: npm ci

            - name: Run npm audit
              run: |
                  echo "Running npm security audit..."
                  npm audit --audit-level=critical

            - name: Check for known vulnerabilities
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install and run audit-ci
              run: |
                  npm install -g audit-ci
                  audit-ci --critical

            - name: Upload security report
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: security-audit-report
                  path: audit-ci-report.json

    dependency-review:
        name: Dependency Review
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Dependency Review
              uses: actions/dependency-review-action@v4
              with:
                  fail-on-severity: moderate
                  allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC

    update-dependencies:
        name: Check for Dependency Updates
        runs-on: ubuntu-latest
        if: github.event_name == 'schedule'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"

            - name: Check for outdated packages
              run: |
                  echo "Checking for outdated packages..."
                  npm outdated --json > outdated.json || true

                  if [ -s outdated.json ]; then
                    echo "📦 Outdated packages found:"
                    cat outdated.json
                    
                    # Create an issue if packages are outdated
                    echo "OUTDATED_PACKAGES=$(cat outdated.json | jq -r 'keys | join(", ")')" >> $GITHUB_ENV
                  else
                    echo "✅ All packages are up to date"
                  fi

            - name: Create issue for outdated dependencies
              if: env.OUTDATED_PACKAGES
              uses: actions/github-script@v7
              with:
                  script: |
                      const outdatedPackages = process.env.OUTDATED_PACKAGES;

                      github.rest.issues.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        title: '📦 Dependency Update Available',
                        body: `## Outdated Dependencies Detected
                        
                        The following packages have updates available:
                        \`\`\`
                        ${outdatedPackages}
                        \`\`\`
                        
                        Please review and update these dependencies to ensure security and performance.
                        
                        Run \`npm outdated\` locally to see detailed version information.
                        
                        _This issue was automatically created by the dependency check workflow._`,
                        labels: ['dependencies', 'maintenance']
                      });

    codeql:
        name: CodeQL Security Analysis
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  languages: javascript

            - name: Autobuild
              uses: github/codeql-action/autobuild@v3

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3
